name: ci

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: ["3.10"]

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          python3.10 -m venv venv
          source venv/bin/activate 
          pip3 install --upgrade pip 
          python3.10 -m pip install -r requirements.txt
          python3.10 setup.py install
      - name: Test with pytest & coverage
        run: |
          source venv/bin/activate
          python3.10 -m pytest --cov=src --cov-report term --cov-report html --cov-report xml -vv
      # TODO requires activation for this repository on codecov website first.
      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v3

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python3.10 -m venv venv
          source venv/bin/activate 
          pip3 install --upgrade pip 
          python3.10 -m pip install -r requirements.txt
          python3.10 setup.py install
      - name: Lint with pylint
        run: |
          source venv/bin/activate
          python3.10 -m pylint $(git ls-files '*.py')
      - name: Lint with mypy
        run: |
          source venv/bin/activate
          python3.10 -m mypy .
